### ISSUE TITLE
`rw_title` function isn't defined

### ISSUE THREAD

**Issue by EnzoMartin** [joshuaiz/plate#10]
The function referenced in `functions.php` to rewrite the title isn't actually defined/available anywhere. Since it's only a warning, PHP/WordPress will swallow it unless you turn on debugging and such

https://github.com/joshuaiz/plate/blob/master/functions.php#L52

However if you want to output the page title inside of meta tags, like so:

```html
<meta property="og:title" content="<?php wp_title() ?>">
```

You'll get this:

```html
<meta property="og:title" content="<br />
<b>Warning</b>:  call_user_func_array() expects parameter 1 to be a valid callback, function 'rw_title' not found or invalid function name in <b>E:\wordpress\wp-includes\class-wp-hook.php</b> on line <b>286</b><br />Just another WordPress Blog">
```

Which doesn't look particularly nice

**Comment by joshuaiz** [comment]
Thanks for this. That title function is actually deprecated so has been removed in the latest commit. Let me know if you still have the error.
