### ISSUE TITLE
Woocommerce

### ISSUE THREAD

**Issue by mktgessentials** [joshuaiz/plate#19]
Are there any WordPress template files already created for plate?  Looking specifically for the main shop template and individual product template.

**Comment by joshuaiz** [comment]
Hey there. While we do support WooCommerce we don't have any ready-to-go product templates that are included but that is not a bad idea. I'll consider putting some basic templates in a further release.

**Comment by thetwopct** [comment]
@mktgessentials I wouldn't advise overriding templates, just use hooks and actions to do what you want. It's future-proofing the changes you make, templates need to be updated too often and cause major issues later on for the website owner. 

https://iconicwp.com/blog/best-way-modify-woocommerce-templates/

**Comment by joshuaiz** [comment]
@thetwopct is correct. I did the whole copy WC templates to my theme thing and they do update them often — or at least more often then you would like — and that means updating all of the files in your theme each time they are updated.

I really like the linked article's approach...in fact, I am going to use it for an update to a client's WooCommerce site that was built with Plate.

**Comment by joshuaiz** [comment]
Considering the above, I think it's best to leave WooCommerce-specific templates out of Plate and let each person choose how to implement WC support in their projects.

Closing this for now.
