### ISSUE TITLE
Will not run on php 5.3.8

### ISSUE THREAD

**Issue by 7SKY** [joshuaiz/plate#20]
Plate doesn't appear to run on php 5.3.8. Consider adding a min php version in readme/requirements file?

At the moment, I am bound to use a server with this lower version of php and having developed a site use plate as a base (first time as I usually use a modded version of bones) I'm only now realizing this of course. 

Hope this helps someone in advance.

**Comment by joshuaiz** [comment]
Hey @7SKY thanks for this report. Any particular errors that you're seeing just so I can be aware?

I didn't test this on anything before php 5.6.X. The minimum php version for current versions of WordPress is 5.6.20 and 5.3.8 came out in 2011(!).

I'll add a min version to the readme and maybe a function that will bail if the php version isn't high enough.

**Comment by 7SKY** [comment]
Appears to die at line 28 of header perhaps due to "get_theme_file_uri" call. The code is not finished after that.
<img width="1141" alt="Screen Shot 2019-09-11 at 7 40 31 PM" src="https://user-images.githubusercontent.com/3410724/64747432-42c2f280-d4cc-11e9-8f02-820e43975f34.png">

**Comment by joshuaiz** [comment]
What version of WordPress are you running? `get_theme_file_uri()` was added relatively recently to WordPress (4.7.0) so it could be outdated WP.

You could try doing find/replace replacing all instances of `get_theme_file_uri()` in the theme (not that many) with `get_template_directory_uri()` or even `get_template_directory()` and see if it runs.

**Comment by 7SKY** [comment]
It's old - 4.6 old. Can't update due to php. I had already tried replacing exactly as you suggested but there appears to be more than that causing it to die. I'm working on getting the host to update or migrate off before a live launch for Friday. Thanks for your help. Plate has got me to finally jump into cssGrid in a way that seems familiar (bones)!

**Comment by joshuaiz** [comment]
Sweetness - glad you're digging Plate.

Hopefully you can convince your host to upgrade as I'm sure you know older versions are huge security risks. I've had to make my case to some small hosts for some clients and usually they come around.

Gonna close this but if anything else comes up don't hesitate to start another issue.
