### ISSUE TITLE
Modernizr script causes page to jump to top

### ISSUE THREAD

**Issue by bestify** [joshuaiz/plate#21]
Thanks for making this theme available. I'm finding it incredibly helpful!

I've noticed that when clicking 'back' in the browser, or linking to a different page with a hash in the URL to anchor to specific section, the browser briefly shows the correct position and then snaps to the top of the page.

Removing the Modernizr script seems to make the issue go away.

Tested in Chrome (Version 78.0.3904.87) and Safari (Version 13.0.3 (14608.3.10.10.1))

**Comment by joshuaiz** [comment]
Thanks for finding this. I update the Modernizr script periodically so I will do some digging and try to find out which part of the script is causing this behavior.

All that said, if you don't need the Modernizr features, you can safely remove.

I'll leave this open for now.

**Comment by joshuaiz** [comment]
Looks like this was addressed in this PR: https://github.com/Modernizr/Modernizr/issues/1781

Going to update the Modernizr package and see if that fixes the issue.

**Comment by joshuaiz** [comment]
@bestify I just pushed up a commit with an updated Modernizr package without hyphens and in my local testing it is going to anchor links without jumping to the top of the page.

If you've made customizations, just grab the current script and replace it in your theme: `/library/js/libs/modernizr-custom-min.js`

https://github.com/joshuaiz/plate/blob/master/library/js/libs/modernizr-custom-min.js

This issue brings up a few thoughts for me:
- do we need to keep including Modernizr, or should we leave this to devs to add what they need?
- if we keep it in, what CSS/js features do we need to support?

Our normal Modernizr build is focused on CSS so I'd be curious to see what other people prioritize...or if they use Modernizr at all.

**Comment by joshuaiz** [comment]
I'm going to close this but if you are still seeing the jump after replacing the script, I'll reopen.
