### ISSUE TITLE
Paragraph Block Preview Error

### ISSUE THREAD

**Issue by bestify** [joshuaiz/plate#23]
Hi Josh,

Not sure if this is something the WP team will fix or whether it's a change that requires new code to be added to the Plate theme?

I've just installed a fresh version of Plate and the new release of WP (5.4)

I noticed that the paragraph block is showing an error: 'This block has encountered an error and cannot be previewed.'

In the console log there's a reference to the react-dom-min.js file and the error: 'm.find is not a function'

Anyway, I hope this is useful, loving your work!

Cheers,

Ash

Edit: Tried switching theme to Twenty Twenty and the issue doesn't occur.

**Comment by joshuaiz** [comment]
Hey @bestify thanks for catching this. I'll take a look tonight and see if I can get a fix up asap.

**Comment by joshuaiz** [comment]
@bestify This should be fixed in the latest master branch as well as the v1.4.1 Release.

The culprit was a bit tricky to find. Looks like WordPress updated the required format for the default `editable-color-palette` array in `theme_support()` however none of the errors would indicate this in the slightest.

If anyone else needs to update their theme(s), in this case, previously I had this:

```php
add_theme_support( 'editor-color-palette',
    array(
        'name' => 'studio bio blue',
        'color' => '#0056ac',
    ),
    // more colors here
);
```

Which needed to be this (with an extra `array` call and slug):

```php
add_theme_support( 'editor-color-palette', array(
    array(
        'name' => __( 'studio bio blue', 'platetheme' ),
        'slug' => 'studio-bio-blue',
        'color' => '#0056ac',
    ),
    // more colors here
) );
```

Maybe that will help some other theme devs.

Let me know if you're still seeing any other issues.

**Comment by joshuaiz** [comment]
Note: if you've already made customizations to Plate and want to fix without updating, you can replace the code in `functions.php` at line 724 from this:

```php
add_theme_support( 'editor-color-palette',
    array(
        'name' => 'studio bio blue',
        'color' => '#0056ac',
    ),
    array(
        'name' => 'studio bio light blue',
        'color' => '#99bbde',
    ),
    array(
        'name' => 'studio bio midnight',
        'color' => '#001c3a',
    ),
    array(
        'name' => 'studio bio purple',
        'color' => '#cc0099',
    ),
    array(
        'name' => 'studio bio red',
        'color' => '#f23e2f',
    ),
    array(
        'name' => 'grey 70',
        'color' => '#444444',
    ),
    array(
        'name' => 'grey 20',
        'color' => '#cccccc',
    )
);
```

...to this:

```php
add_theme_support( 'editor-color-palette', array(
    array(
        'name' => __( 'studio bio blue', 'platetheme' ),
        'slug' => 'studio-bio-blue',
        'color' => '#0056ac',
    ),
    array(
        'name' => __( 'studio bio light blue', 'platetheme' ),
        'slug' => 'studio-bio-light-blue',
        'color' => '#99bbde',
    ),
    array(
        'name' => __( 'studio bio midnight', 'platetheme' ),
        'slug' => 'studio-bio-midnight',
        'color' => '#001c3a',
    ),
    array(
        'name' => __( 'studio bio purple', 'platetheme' ),
        'slug' => 'studio-bio-purple',
        'color' => '#cc0099',
    ),
    array(
        'name' => __( 'studio bio red', 'platetheme' ),
        'slug' => 'studio-bio-red',
        'color' => '#f23e2f',
    ),
    array(
        'name' => __( 'grey 70', 'platetheme' ),
        'slug' => 'grey-70',
        'color' => '#444444',
    ),
    array(
        'name' => __( 'grey 20', 'platetheme' ),
        'slug' => 'grey-20',
        'color' => '#cccccc',
    ),
) );
```

Alternatively, you can just comment that section out in the `plate_theme_support()` function.

**Comment by bestify** [comment]
@joshuaiz You legend! I can imagine that was a tricky one to track down.

Thanks for reacting to this quickly, really appreciate it. I chucked a small token of my gratitude to your PayPal 👍

Ash

**Comment by joshuaiz** [comment]
@bestify Thanks so much...really appreciate it.

**Comment by joshuaiz** [comment]
Gonna close this. If you run into any other errors, submit a new issue.
