### ISSUE TITLE
Do Quicktags work out of the box?

### ISSUE THREAD

**Issue by rgfx** [joshuaiz/plate#3]
No experience working with quicktags, is there something I need to do make them work? This how my editor looks. 

![editor](https://user-images.githubusercontent.com/2388078/31262182-8c7dac40-aa16-11e7-955e-bc88ad60a004.jpg)

**Comment by joshuaiz** [comment]
Quicktags are only for the Text editor which you should be using instead of the Visual editor in your pic. If you switch to the Text editor you will see them.

**Comment by rgfx** [comment]
Oh when you said "clients", I was thinking text editor was off limits :) Pretty cool, thanks

**Comment by joshuaiz** [comment]
No worries @rgfx. Even though it's hard, you should try to get your clients to only use the Text editor. If you're setting up the accounts for them you can disable it in their profile.

Adding these extra Quicktags should help them. And even if it is you entering content they help with that too.

**Comment by rgfx** [comment]
@joshuaiz that would certainly make my job easier, doesn't the text editor frighten your clients... Maybe your clients are more tech savvy than mine. 

Find it challenging sometimes to teach them how to use WordPress.  But your right, with Quicktags I have a chance to play less website clean-up-crew.

 Thanks.
