### ISSUE TITLE
Error with comments on single.php

### ISSUE THREAD

**Issue by thetwopct** [joshuaiz/plate#6]
Firstly, I've just started migrating from Bones to Plate, thanks for keeping it going and now making it your own, the updates you have done are much appreciated. 

Secondly, I think I've discovered an issue with comments when viewing single.php. Testing with fresh 4.9.4 Wordpress and fresh Plate clone. Where the comments should be is:

`Warning: call_user_func() expects parameter 1 to be a valid callback, function 'template_comments' not found or invalid function name in /Users/james 1/Dropbox/Websites/acaciabeauty/wp-includes/class-walker-comment.php on line 174`

Screenshot - http://take.ms/8Go9cS

I've tried removing some of the comment related stuff in functions.php but thats not it.

**Comment by joshuaiz** [comment]
Thanks for catching this. In comments.php on line 26 change this:

    'callback'          => 'template_comments', 

to

     'callback'          => 'plate_comments'

That should fix it. Let me know if it doesn't.

**Comment by joshuaiz** [comment]
Tested locally and I've pushed this change up.
