### ISSUE TITLE
User Agent styling

### ISSUE THREAD

**Issue by thetwopct** [joshuaiz/plate#7]
Apologies if this is a dumb question and possibly nothing to do with Plate/Bones but do you know why User Agent styling is applied to elements on a page? Like this is being applied to a H3 tag, but fi I try and edit I can't find these values anywhere in the theme 

``
display: block;
font-size: 1.17em;
-webkit-margin-before: 1em;
-webkit-margin-after: 1em;
-webkit-margin-start: 0px;
-webkit-margin-end: 0px;
font-weight: bold;
``

**Comment by joshuaiz** [comment]
@thetwopct It's not a dumb question at all. Those css values are not in the theme and come from the browser defaults. As much as we try to regulate those with normalize.css and other default settings there is no way to catch every edge case.

Thus, if you can localize it to your browser or a particular browser's default styles, even though Chris Coyier would yell at you, sometimes you need the !important flag to override browser styles.

You know what? Nobody else knows that you've used !important. So if you need it in specific situations, use it! That's what it is there for.

Granted, I try to avoid using !important as it usually means you haven't structured your HTML properly or have assigned nested css ids or classes in a non-semantic way but even if that is the case, sometimes you need to explicitly override browser (user agent) styles. So do it.
