### ISSUE TITLE
Bones compatibility

### ISSUE THREAD

**Issue by omerida** [joshuaiz/plate#9]
If I have a bones theme, can I extend plates instead?

**Comment by joshuaiz** [comment]
@omerida I'm not exactly sure what you're asking. Can you explain a bit more?

They are separate themes so if you have made customizations to Bones and then activated Plate, it wouldn't 'extend' Bones, it would just be a separate theme and your customizations would still be with Bones.

**Comment by omerida** [comment]
I have a client with a bones based theme that is looking to update it. I think they're theme is a child theme of bones... was wondering if I changed the parent to plate if it'd "just work"

**Comment by joshuaiz** [comment]
Unfortunately that wouldn't work. You would have to create a child theme of Plate. 

Going to close this but feel free to start a new issue with any more questions.
